// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;
using System.Collections;

namespace Hostile
{
	namespace SimplePool
	{
		using Core;
		namespace Components
		{
			public abstract class BasePoolComponent : MonoBehaviour
			{
				private SimplePool _pool;

				public SimplePool pool {
					get
					{
						return _pool;
					}
				}

				public void OnCreatedByPool( SimplePool pool )
				{
					_pool = pool;
				}

				public abstract void OnSpawn();
				public abstract void OnDespawn();
			}
		}
	}
}

